package com.kekecreations.arts_and_crafts.core.registry;

import com.kekecreations.arts_and_crafts.core.misc.RegistryHelper;
import dev.architectury.registry.registries.RegistrySupplier;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.WallBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;

public class KekeBlocks {

    //CHALK BLOCKS - BLOCKS ARE IN ORDER WITH TEXTURE FILE NAMES
    public static final RegistrySupplier<Block> BLACK_CHALK = RegistryHelper.BLOCKS.register("black_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BLACK_CHALK_ITEM = RegistryHelper.ITEMS.register("black_chalk", () -> new BlockItem(BLACK_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> BLUE_CHALK = RegistryHelper.BLOCKS.register("blue_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.BLUE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BLUE_CHALK_ITEM = RegistryHelper.ITEMS.register("blue_chalk", () -> new BlockItem(BLUE_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> BROWN_CHALK = RegistryHelper.BLOCKS.register("brown_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BROWN_CHALK_ITEM = RegistryHelper.ITEMS.register("brown_chalk", () -> new BlockItem(BROWN_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> CYAN_CHALK = RegistryHelper.BLOCKS.register("cyan_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.CYAN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> CYAN_CHALK_ITEM = RegistryHelper.ITEMS.register("cyan_chalk", () -> new BlockItem(CYAN_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> GRAY_CHALK = RegistryHelper.BLOCKS.register("gray_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> GRAY_CHALK_ITEM = RegistryHelper.ITEMS.register("gray_chalk", () -> new BlockItem(GRAY_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> GREEN_CHALK = RegistryHelper.BLOCKS.register("green_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.GREEN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> GREEN_CHALK_ITEM = RegistryHelper.ITEMS.register("green_chalk", () -> new BlockItem(GREEN_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> LIGHT_BLUE_CHALK = RegistryHelper.BLOCKS.register("light_blue_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.LIGHT_BLUE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIGHT_BLUE_CHALK_ITEM = RegistryHelper.ITEMS.register("light_blue_chalk", () -> new BlockItem(LIGHT_BLUE_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> LIGHT_GRAY_CHALK = RegistryHelper.BLOCKS.register("light_gray_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.LIGHT_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIGHT_GRAY_CHALK_ITEM = RegistryHelper.ITEMS.register("light_gray_chalk", () -> new BlockItem(LIGHT_GRAY_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> LIME_CHALK = RegistryHelper.BLOCKS.register("lime_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.LIME).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIME_CHALK_ITEM = RegistryHelper.ITEMS.register("lime_chalk", () -> new BlockItem(LIME_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> MAGENTA_CHALK = RegistryHelper.BLOCKS.register("magenta_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.MAGENTA).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> MAGENTA_CHALK_ITEM = RegistryHelper.ITEMS.register("magenta_chalk", () -> new BlockItem(MAGENTA_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> ORANGE_CHALK = RegistryHelper.BLOCKS.register("orange_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> ORANGE_CHALK_ITEM = RegistryHelper.ITEMS.register("orange_chalk", () -> new BlockItem(ORANGE_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> PINK_CHALK = RegistryHelper.BLOCKS.register("pink_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.PINK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> PINK_CHALK_ITEM = RegistryHelper.ITEMS.register("pink_chalk", () -> new BlockItem(PINK_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> PURPLE_CHALK = RegistryHelper.BLOCKS.register("purple_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.PURPLE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> PURPLE_CHALK_ITEM = RegistryHelper.ITEMS.register("purple_chalk", () -> new BlockItem(PURPLE_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> RED_CHALK = RegistryHelper.BLOCKS.register("red_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> RED_CHALK_ITEM = RegistryHelper.ITEMS.register("red_chalk", () -> new BlockItem(RED_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> WHITE_CHALK = RegistryHelper.BLOCKS.register("white_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> WHITE_CHALK_ITEM = RegistryHelper.ITEMS.register("white_chalk", () -> new BlockItem(WHITE_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<Block> YELLOW_CHALK = RegistryHelper.BLOCKS.register("yellow_chalk", () -> new Block(BlockBehaviour.Properties.of().mapColor(DyeColor.YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> YELLOW_CHALK_ITEM = RegistryHelper.ITEMS.register("yellow_chalk", () -> new BlockItem(YELLOW_CHALK.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));

    //CHALK SLABS
    public static final RegistrySupplier<SlabBlock> BLACK_CHALK_SLAB = RegistryHelper.BLOCKS.register("black_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BLACK_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("black_chalk_slab", () -> new BlockItem(BLACK_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> BLUE_CHALK_SLAB = RegistryHelper.BLOCKS.register("blue_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.BLUE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BLUE_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("blue_chalk_slab", () -> new BlockItem(BLUE_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> BROWN_CHALK_SLAB = RegistryHelper.BLOCKS.register("brown_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BROWN_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("brown_chalk_slab", () -> new BlockItem(BROWN_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> CYAN_CHALK_SLAB = RegistryHelper.BLOCKS.register("cyan_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.CYAN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> CYAN_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("cyan_chalk_slab", () -> new BlockItem(CYAN_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> GRAY_CHALK_SLAB = RegistryHelper.BLOCKS.register("gray_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> GRAY_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("gray_chalk_slab", () -> new BlockItem(GRAY_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> GREEN_CHALK_SLAB = RegistryHelper.BLOCKS.register("green_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.GREEN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> GREEN_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("green_chalk_slab", () -> new BlockItem(GREEN_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> LIGHT_BLUE_CHALK_SLAB = RegistryHelper.BLOCKS.register("light_blue_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.LIGHT_BLUE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIGHT_BLUE_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("light_blue_chalk_slab", () -> new BlockItem(LIGHT_BLUE_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> LIGHT_GRAY_CHALK_SLAB = RegistryHelper.BLOCKS.register("light_gray_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.LIGHT_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIGHT_GRAY_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("light_gray_chalk_slab", () -> new BlockItem(LIGHT_GRAY_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> LIME_CHALK_SLAB = RegistryHelper.BLOCKS.register("lime_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.LIME).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIME_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("lime_chalk_slab", () -> new BlockItem(LIME_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> MAGENTA_CHALK_SLAB = RegistryHelper.BLOCKS.register("magenta_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.MAGENTA).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> MAGENTA_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("magenta_chalk_slab", () -> new BlockItem(MAGENTA_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> ORANGE_CHALK_SLAB = RegistryHelper.BLOCKS.register("orange_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> ORANGE_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("orange_chalk_slab", () -> new BlockItem(ORANGE_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> PINK_CHALK_SLAB = RegistryHelper.BLOCKS.register("pink_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.PINK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> PINK_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("pink_chalk_slab", () -> new BlockItem(PINK_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> PURPLE_CHALK_SLAB = RegistryHelper.BLOCKS.register("purple_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.PURPLE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> PURPLE_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("purple_chalk_slab", () -> new BlockItem(PURPLE_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> RED_CHALK_SLAB = RegistryHelper.BLOCKS.register("red_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> RED_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("red_chalk_slab", () -> new BlockItem(RED_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> WHITE_CHALK_SLAB = RegistryHelper.BLOCKS.register("white_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> WHITE_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("white_chalk_slab", () -> new BlockItem(WHITE_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<SlabBlock> YELLOW_CHALK_SLAB = RegistryHelper.BLOCKS.register("yellow_chalk_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> YELLOW_CHALK_SLAB_ITEM = RegistryHelper.ITEMS.register("yellow_chalk_slab", () -> new BlockItem(YELLOW_CHALK_SLAB.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));

    //CHALK WALL
    public static final RegistrySupplier<WallBlock> BLACK_CHALK_WALL = RegistryHelper.BLOCKS.register("black_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BLACK_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("black_chalk_wall", () -> new BlockItem(BLACK_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> BLUE_CHALK_WALL = RegistryHelper.BLOCKS.register("blue_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.BLUE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BLUE_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("blue_chalk_wall", () -> new BlockItem(BLUE_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> BROWN_CHALK_WALL = RegistryHelper.BLOCKS.register("brown_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BROWN_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("brown_chalk_wall", () -> new BlockItem(BROWN_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> CYAN_CHALK_WALL = RegistryHelper.BLOCKS.register("cyan_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.CYAN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> CYAN_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("cyan_chalk_wall", () -> new BlockItem(CYAN_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> GRAY_CHALK_WALL = RegistryHelper.BLOCKS.register("gray_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> GRAY_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("gray_chalk_wall", () -> new BlockItem(GRAY_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> GREEN_CHALK_WALL = RegistryHelper.BLOCKS.register("green_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.GREEN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> GREEN_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("green_chalk_wall", () -> new BlockItem(GREEN_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> LIGHT_BLUE_CHALK_WALL = RegistryHelper.BLOCKS.register("light_blue_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.LIGHT_BLUE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIGHT_BLUE_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("light_blue_chalk_wall", () -> new BlockItem(LIGHT_BLUE_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> LIGHT_GRAY_CHALK_WALL = RegistryHelper.BLOCKS.register("light_gray_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.LIGHT_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIGHT_GRAY_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("light_gray_chalk_wall", () -> new BlockItem(LIGHT_GRAY_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> LIME_CHALK_WALL = RegistryHelper.BLOCKS.register("lime_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.LIME).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIME_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("lime_chalk_wall", () -> new BlockItem(LIME_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> MAGENTA_CHALK_WALL = RegistryHelper.BLOCKS.register("magenta_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.MAGENTA).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> MAGENTA_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("magenta_chalk_wall", () -> new BlockItem(MAGENTA_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> ORANGE_CHALK_WALL = RegistryHelper.BLOCKS.register("orange_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> ORANGE_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("orange_chalk_wall", () -> new BlockItem(ORANGE_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> PINK_CHALK_WALL = RegistryHelper.BLOCKS.register("pink_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.PINK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> PINK_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("pink_chalk_wall", () -> new BlockItem(PINK_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> PURPLE_CHALK_WALL = RegistryHelper.BLOCKS.register("purple_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.PURPLE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> PURPLE_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("purple_chalk_wall", () -> new BlockItem(PURPLE_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> RED_CHALK_WALL = RegistryHelper.BLOCKS.register("red_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> RED_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("red_chalk_wall", () -> new BlockItem(RED_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> WHITE_CHALK_WALL = RegistryHelper.BLOCKS.register("white_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> WHITE_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("white_chalk_wall", () -> new BlockItem(WHITE_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<WallBlock> YELLOW_CHALK_WALL = RegistryHelper.BLOCKS.register("yellow_chalk_wall", () -> new WallBlock(BlockBehaviour.Properties.of().mapColor(DyeColor.YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> YELLOW_CHALK_WALL_ITEM = RegistryHelper.ITEMS.register("yellow_chalk_wall", () -> new BlockItem(YELLOW_CHALK_WALL.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));

    //CHALK STAIRS
    public static final RegistrySupplier<StairBlock> BLACK_CHALK_STAIRS = RegistryHelper.BLOCKS.register("black_chalk_stairs", () -> new StairBlock(BLACK_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BLACK_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("black_chalk_stairs", () -> new BlockItem(BLACK_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> BLUE_CHALK_STAIRS = RegistryHelper.BLOCKS.register("blue_chalk_stairs", () -> new StairBlock(BLUE_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.BLUE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BLUE_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("blue_chalk_stairs", () -> new BlockItem(BLUE_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> BROWN_CHALK_STAIRS = RegistryHelper.BLOCKS.register("brown_chalk_stairs", () -> new StairBlock(BROWN_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> BROWN_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("brown_chalk_stairs", () -> new BlockItem(BROWN_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> CYAN_CHALK_STAIRS = RegistryHelper.BLOCKS.register("cyan_chalk_stairs", () -> new StairBlock(CYAN_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.CYAN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> CYAN_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("cyan_chalk_stairs", () -> new BlockItem(CYAN_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> GRAY_CHALK_STAIRS = RegistryHelper.BLOCKS.register("gray_chalk_stairs", () -> new StairBlock(GRAY_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> GRAY_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("gray_chalk_stairs", () -> new BlockItem(GRAY_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> GREEN_CHALK_STAIRS = RegistryHelper.BLOCKS.register("green_chalk_stairs", () -> new StairBlock(GREEN_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.GREEN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> GREEN_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("green_chalk_stairs", () -> new BlockItem(GREEN_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> LIGHT_BLUE_CHALK_STAIRS = RegistryHelper.BLOCKS.register("light_blue_chalk_stairs", () -> new StairBlock(LIGHT_BLUE_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.LIGHT_BLUE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIGHT_BLUE_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("light_blue_chalk_stairs", () -> new BlockItem(LIGHT_BLUE_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> LIGHT_GRAY_CHALK_STAIRS = RegistryHelper.BLOCKS.register("light_gray_chalk_stairs", () -> new StairBlock(LIGHT_GRAY_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.LIGHT_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIGHT_GRAY_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("light_gray_chalk_stairs", () -> new BlockItem(LIGHT_GRAY_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> LIME_CHALK_STAIRS = RegistryHelper.BLOCKS.register("lime_chalk_stairs", () -> new StairBlock(LIME_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.LIME).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> LIME_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("lime_chalk_stairs", () -> new BlockItem(LIME_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> MAGENTA_CHALK_STAIRS = RegistryHelper.BLOCKS.register("magenta_chalk_stairs", () -> new StairBlock(MAGENTA_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.MAGENTA).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> MAGENTA_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("magenta_chalk_stairs", () -> new BlockItem(MAGENTA_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> ORANGE_CHALK_STAIRS = RegistryHelper.BLOCKS.register("orange_chalk_stairs", () -> new StairBlock(ORANGE_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> ORANGE_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("orange_chalk_stairs", () -> new BlockItem(ORANGE_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> PINK_CHALK_STAIRS = RegistryHelper.BLOCKS.register("pink_chalk_stairs", () -> new StairBlock(PINK_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.PINK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> PINK_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("pink_chalk_stairs", () -> new BlockItem(PINK_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> PURPLE_CHALK_STAIRS = RegistryHelper.BLOCKS.register("purple_chalk_stairs", () -> new StairBlock(PURPLE_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.PURPLE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> PURPLE_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("purple_chalk_stairs", () -> new BlockItem(PURPLE_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> RED_CHALK_STAIRS = RegistryHelper.BLOCKS.register("red_chalk_stairs", () -> new StairBlock(RED_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> RED_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("red_chalk_stairs", () -> new BlockItem(RED_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> WHITE_CHALK_STAIRS = RegistryHelper.BLOCKS.register("white_chalk_stairs", () -> new StairBlock(WHITE_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> WHITE_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("white_chalk_stairs", () -> new BlockItem(WHITE_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));
    public static final RegistrySupplier<StairBlock> YELLOW_CHALK_STAIRS = RegistryHelper.BLOCKS.register("yellow_chalk_stairs", () -> new StairBlock(YELLOW_CHALK.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(DyeColor.YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8f)));
    public static final RegistrySupplier<BlockItem> YELLOW_CHALK_STAIRS_ITEM = RegistryHelper.ITEMS.register("yellow_chalk_stairs", () -> new BlockItem(YELLOW_CHALK_STAIRS.get(), new Item.Properties().arch$tab(CreativeModeTabs.COLORED_BLOCKS)));


    public static void register() {
    }
}
