package com.kekecreations.arts_and_crafts.fabric.core.datagen.server;

import com.kekecreations.arts_and_crafts.core.registry.KekeBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;

public class ArtsAndCraftLootTableGenerator extends FabricBlockLootTableProvider {

    public ArtsAndCraftLootTableGenerator(FabricDataOutput dataOutput) {
        super(dataOutput);
    }

    @Override
    public void generate() {
        terracottaShingles();
        chalk();

    }
    private void terracottaShingles() {
        dropSelf(KekeBlocks.TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.BLACK_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.BLUE_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.BROWN_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.LIGHT_BLUE_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.GRAY_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.WHITE_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.CYAN_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.GREEN_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.LIGHT_GRAY_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.LIME_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.MAGENTA_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.ORANGE_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.PINK_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.PURPLE_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.RED_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.YELLOW_TERRACOTTA_SHINGLES.get());
        dropSelf(KekeBlocks.BLACK_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.BLUE_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.BROWN_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.LIGHT_BLUE_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.GRAY_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.WHITE_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.CYAN_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.GREEN_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.LIGHT_GRAY_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.LIME_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.MAGENTA_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.ORANGE_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.PINK_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.PURPLE_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.RED_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.YELLOW_TERRACOTTA_SHINGLE_SLAB.get());
        dropSelf(KekeBlocks.BLACK_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.BLUE_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.BROWN_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.LIGHT_BLUE_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.GRAY_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.WHITE_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.CYAN_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.GREEN_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.LIGHT_GRAY_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.LIME_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.MAGENTA_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.ORANGE_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.PINK_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.PURPLE_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.RED_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.YELLOW_TERRACOTTA_SHINGLE_WALL.get());
        dropSelf(KekeBlocks.BLACK_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.BLUE_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.BROWN_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.LIGHT_BLUE_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.GRAY_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.WHITE_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.CYAN_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.GREEN_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.LIGHT_GRAY_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.LIME_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.MAGENTA_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.ORANGE_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.PINK_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.PURPLE_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.RED_TERRACOTTA_SHINGLE_STAIRS.get());
        dropSelf(KekeBlocks.YELLOW_TERRACOTTA_SHINGLE_STAIRS.get());
    }
    private void chalk() {
        dropSelf(KekeBlocks.BLACK_CHALK.get());
        dropSelf(KekeBlocks.BLUE_CHALK.get());
        dropSelf(KekeBlocks.BROWN_CHALK.get());
        dropSelf(KekeBlocks.LIGHT_BLUE_CHALK.get());
        dropSelf(KekeBlocks.GRAY_CHALK.get());
        dropSelf(KekeBlocks.WHITE_CHALK.get());
        dropSelf(KekeBlocks.CYAN_CHALK.get());
        dropSelf(KekeBlocks.GREEN_CHALK.get());
        dropSelf(KekeBlocks.LIGHT_GRAY_CHALK.get());
        dropSelf(KekeBlocks.LIME_CHALK.get());
        dropSelf(KekeBlocks.MAGENTA_CHALK.get());
        dropSelf(KekeBlocks.ORANGE_CHALK.get());
        dropSelf(KekeBlocks.PINK_CHALK.get());
        dropSelf(KekeBlocks.PURPLE_CHALK.get());
        dropSelf(KekeBlocks.RED_CHALK.get());
        dropSelf(KekeBlocks.YELLOW_CHALK.get());
        dropSelf(KekeBlocks.BLACK_CHALK_SLAB.get());
        dropSelf(KekeBlocks.BLUE_CHALK_SLAB.get());
        dropSelf(KekeBlocks.BROWN_CHALK_SLAB.get());
        dropSelf(KekeBlocks.LIGHT_BLUE_CHALK_SLAB.get());
        dropSelf(KekeBlocks.GRAY_CHALK_SLAB.get());
        dropSelf(KekeBlocks.WHITE_CHALK_SLAB.get());
        dropSelf(KekeBlocks.CYAN_CHALK_SLAB.get());
        dropSelf(KekeBlocks.GREEN_CHALK_SLAB.get());
        dropSelf(KekeBlocks.LIGHT_GRAY_CHALK_SLAB.get());
        dropSelf(KekeBlocks.LIME_CHALK_SLAB.get());
        dropSelf(KekeBlocks.MAGENTA_CHALK_SLAB.get());
        dropSelf(KekeBlocks.ORANGE_CHALK_SLAB.get());
        dropSelf(KekeBlocks.PINK_CHALK_SLAB.get());
        dropSelf(KekeBlocks.PURPLE_CHALK_SLAB.get());
        dropSelf(KekeBlocks.RED_CHALK_SLAB.get());
        dropSelf(KekeBlocks.YELLOW_CHALK_SLAB.get());
        dropSelf(KekeBlocks.BLACK_CHALK_WALL.get());
        dropSelf(KekeBlocks.BLUE_CHALK_WALL.get());
        dropSelf(KekeBlocks.BROWN_CHALK_WALL.get());
        dropSelf(KekeBlocks.LIGHT_BLUE_CHALK_WALL.get());
        dropSelf(KekeBlocks.GRAY_CHALK_WALL.get());
        dropSelf(KekeBlocks.WHITE_CHALK_WALL.get());
        dropSelf(KekeBlocks.CYAN_CHALK_WALL.get());
        dropSelf(KekeBlocks.GREEN_CHALK_WALL.get());
        dropSelf(KekeBlocks.LIGHT_GRAY_CHALK_WALL.get());
        dropSelf(KekeBlocks.LIME_CHALK_WALL.get());
        dropSelf(KekeBlocks.MAGENTA_CHALK_WALL.get());
        dropSelf(KekeBlocks.ORANGE_CHALK_WALL.get());
        dropSelf(KekeBlocks.PINK_CHALK_WALL.get());
        dropSelf(KekeBlocks.PURPLE_CHALK_WALL.get());
        dropSelf(KekeBlocks.RED_CHALK_WALL.get());
        dropSelf(KekeBlocks.YELLOW_CHALK_WALL.get());
        dropSelf(KekeBlocks.BLACK_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.BLUE_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.BROWN_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.LIGHT_BLUE_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.GRAY_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.WHITE_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.CYAN_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.GREEN_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.LIGHT_GRAY_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.LIME_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.MAGENTA_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.ORANGE_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.PINK_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.PURPLE_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.RED_CHALK_STAIRS.get());
        dropSelf(KekeBlocks.YELLOW_CHALK_STAIRS.get());
    }
}
